import { StateGraph, type GraphNode, StateSchema, START, END, type CompiledStateGraph } from "@langchain/langgraph";
import z from "zod";
import { createAgent, HumanMessage, providerStrategy } from "langchain";
import { model_1, model_2, geminiModel } from "./model.ai.js";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [geminiResponse, groqResponse] = await Promise.all([
    model_1.invoke(state.problem),
    model_2.invoke(state.problem),
  ]);

  return {
    solution_1: geminiResponse.text,
    solution_2: groqResponse.text,
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;
  const judge = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_reasoning: z.string(),
        solution_2_reasoning: z.string(),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating solutions generated by different two AI models. You will score each solution from 0 to 10 based on correctness, efficiency, and clarity. You will also provide reasoning for your scores.`,
  });

  const judgeResponse = await judge.invoke({
    messages: [new HumanMessage(`
      Problem: ${problem}
      Solution_1: ${solution_1}
      Solution_2: ${solution_2}
      Please evaluate the solution and porvide the scores and reasoning
      `)]
  })

  const { solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning } = judgeResponse.structuredResponse

  return {
    judge: {
      solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning
    }
  }
};

const graph = new StateGraph(state)
  .addNode("solution", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge_node")
  .addEdge("judge_node", END)
  .compile()

export default async function (problem: string) {
  const result = await graph.invoke({ problem })
  return result
}