import { StateGraph, type GraphNode, StateSchema, START, END, CompiledStateGraph } from "@langchain/langgraph";
import z from "zod";
import { createAgent, HumanMessage, SystemMessage, providerStrategy } from "langchain";
import { model_1, model_2, geminiModel } from "./model.ai.js";
import type { AIMessage } from "@langchain/core/messages";




const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
  }).default({
    solution_1_score: 0,
    solution_2_score: 0,
    solution_1_reasoning: "",
    solution_2_reasoning: "",
  }),
});

const solutionNode: GraphNode<typeof state> = async (state) => {
  console.log("🚀 SolutionNode started, problem:", state.problem);
  const [geminiResponse, groqResponse] = await Promise.all([
    model_1.invoke([new HumanMessage(state.problem)]) as Promise<AIMessage>,
    model_2.invoke([new HumanMessage(state.problem)]) as Promise<AIMessage>,
  ]);

  const text1 = typeof geminiResponse.content === "string" ? geminiResponse.content : JSON.stringify(geminiResponse.content);
  const text2 = typeof groqResponse.content === "string" ? groqResponse.content : JSON.stringify(groqResponse.content);

  console.log("🚀 SolutionNode completed, solution_1:", text1);
  console.log("🚀 SolutionNode completed, solution_2:", text2);
  return {
    solution_1: text1,
    solution_2: text2,
  };
};

const judgeNode: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  try {
    
    const judge = geminiModel.withStructuredOutput(z.object({
      solution_1_score: z.number().min(0).max(10),
      solution_2_score: z.number().min(0).max(10),
      solution_1_reasoning: z.string(),
      solution_2_reasoning: z.string(),
    }));
  
    const judgeResponse = await judge.invoke(
      [new SystemMessage(
        `You are a judge tasked with evaluating solutions generated by two AI models. Score each solution from 0 to 10 based on correctness, efficiency, and clarity. Provide reasoning for each score.`
      ),
      new HumanMessage(`
        Problem: ${problem}
        Solution_1: ${solution_1}
        Solution_2: ${solution_2}
        Please evaluate the solution and provide the scores and reasoning
        `)]
    )
  
    const { solution_1_score, solution_2_score, solution_1_reasoning, solution_2_reasoning } = judgeResponse
  
    return {
      judge: {
        solution_1_score: judgeResponse.solution_1_score, 
        solution_2_score: judgeResponse.solution_2_score, 
        solution_1_reasoning:judgeResponse.solution_1_reasoning, 
        solution_2_reasoning: judgeResponse.solution_2_reasoning
      }
    }
  } catch (err) {
    console.error("❌ Judge failed:", err);
    // graceful fallback — judge না থাকলেও frontend কিছু পাবে
    return {
      judge: {
        solution_1_score: 0,
        solution_2_score: 0,
        solution_1_reasoning:
          "⚠️ Judge model was unavailable (API overload). Please try again.",
        solution_2_reasoning:
          "⚠️ Judge model was unavailable (API overload). Please try again.",
      },
    }
  }
};

const graph: CompiledStateGraph<typeof state, any> = new StateGraph(state)
  .addNode("solution", solutionNode)
  .addNode("judge_node", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge_node")
  .addEdge("judge_node", END)
  .compile()

export default async function (problem: string) {
  const result = await graph.invoke({ problem })
  return result
}